apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
spec:
  template:
    spec:
      containers:
      - name: postgres-operator
        env:
        - name: WATCHED_NAMESPACE
          value: '*'
